{{- if and .Values.rbac.setupSecurityContext (not (.Capabilities.APIVersions.Has "security.openshift.io/v1")) }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "network-latency-exporter.name" . }}
spec:
  privileged: false
  hostPID: false
  hostIPC: false
  hostNetwork: false
  volumes:
    - 'configMap'
    - 'secret'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  allowPrivilegeEscalation: false
  seLinux:
    rule: 'RunAsAny'
  allowedCapabilities: []
{{- end }}
