apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-latency-exporter.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "network-latency-exporter.name" . }}
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: telegraf-statsd
      port: 8125
      protocol: TCP
    - name: telegraf-tcp
      port: 8094
      protocol: TCP
    - name: telegraf-udp
      port: 8092
      protocol: UDP
    - name: metrics
      port: 9273
      targetPort: 9273
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "network-latency-exporter.name" . }}
